"use client";

import React, { useState } from "react";
import {
  Download,
  Film,
  Play,
  FileText,
  Terminal,
  Check,
  Copy,
  ExternalLink,
  AlertCircle,
  Eye,
  Calendar,
  Sparkles,
  Sliders,
  FolderDown,
  Music,
  Video,
  Trash2,
} from "lucide-react";

interface FormatOption {
  id: string;
  format: string;
  quality: string;
  resolution?: string;
  extension: "mp4" | "webm" | "mp3" | "m4a" | "wav" | "srt" | "vtt";
  hasVideo: boolean;
  hasAudio: boolean;
  fileSizeEstimate: string;
  bitrate?: string;
  streamUrl: string;
}

interface ThumbnailOption {
  label: string;
  url: string;
  resolution: string;
}

interface MediaAnalysis {
  url: string;
  platform: string;
  platformId: string;
  isCourseOrPlaylist: boolean;
  videoId?: string;
  metadata: {
    title: string;
    author: string;
    thumbnail: string;
    duration: string;
    views: string;
    uploadDate: string;
    description: string;
    directStreamUrl?: string | null;
  };
  formats: FormatOption[];
  thumbnails: ThumbnailOption[];
  subtitles: Array<{
    language: string;
    code: string;
    format: string;
    isAutoGenerated: boolean;
  }>;
  commands: {
    ytdlp: string;
  };
  ytDlpEngine?: {
    embedded: boolean;
    version: string;
    source: string;
    extractedViaYtDlp: boolean;
  };
}

interface DownloadTask {
  id: string;
  title: string;
  quality: string;
  format: string;
  fileSize: string;
  progress: number;
  status: "downloading" | "completed" | "error";
  timestamp: string;
}

const PRESET_URLS = [
  { label: "Direct MP4 Video (Instant Download)", url: "https://www.w3schools.com/html/mov_bbb.mp4" },
  { label: "Direct HD Clip (Instant Download)", url: "https://raw.githubusercontent.com/bower-media-samples/big-buck-bunny-480p-30s/master/video.mp4" },
  { label: "YouTube Video", url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ" },
  { label: "Vimeo Creative", url: "https://vimeo.com/76979871" },
];

interface DownloadErrorInfo {
  url: string;
  title: string;
  error: string;
  details: string;
  statusCode?: number;
  requiresLocalEngine?: boolean;
  ytdlpCommand?: string;
}

export function AnyVideoDownloaderTool({ isStandalone = false }: { isStandalone?: boolean }) {
  const [inputUrl, setInputUrl] = useState("https://www.w3schools.com/html/mov_bbb.mp4");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<DownloadErrorInfo | null>(null);
  const [result, setResult] = useState<MediaAnalysis | null>(null);
  const [activeTab, setActiveTab] = useState<"formats" | "player" | "subtitles" | "ytdlp" | "queue">("formats");
  const [formatFilter, setFormatFilter] = useState<"all" | "video" | "audio">("all");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [downloadTasks, setDownloadTasks] = useState<DownloadTask[]>([]);

  // yt-dlp Flag Customizer States
  const [ytdlpFormat, setYtdlpFormat] = useState("bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best");
  const [ytdlpExtractAudio, setYtdlpExtractAudio] = useState(false);
  const [ytdlpAudioFormat, setYtdlpAudioFormat] = useState<"mp3" | "m4a" | "wav" | "flac" | "opus">("mp3");
  const [ytdlpSubtitles, setYtdlpSubtitles] = useState(true);
  const [ytdlpSubLang, setYtdlpSubLang] = useState("en.*");
  const [ytdlpEmbedThumb, setYtdlpEmbedThumb] = useState(true);
  const [ytdlpEmbedMeta, setYtdlpEmbedMeta] = useState(true);
  const [ytdlpSponsorBlock, setYtdlpSponsorBlock] = useState(false);
  const [ytdlpRateLimit, setYtdlpRateLimit] = useState("none");
  const [ytdlpBrowserCookies, setYtdlpBrowserCookies] = useState("none");

  const handleAnalyze = async (urlToAnalyze?: string, autoDownloadBest = false) => {
    const target = (urlToAnalyze || inputUrl).trim();
    if (!target) return;

    setLoading(true);
    setError(null);
    setDownloadError(null);

    try {
      const res = await fetch("/api/tools/omniget", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: target }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Failed to parse media URL.");
      }

      setResult(data);
      setActiveTab("formats");

      if (autoDownloadBest && data.formats && data.formats.length > 0) {
        const best = data.formats.find((f: FormatOption) => f.quality.includes("1080p")) || data.formats[0];
        triggerRealDownload(
          best.streamUrl,
          data.metadata?.title || "video",
          best.quality,
          best.extension,
          best.fileSizeEstimate
        );
      }
    } catch (err: any) {
      setError(err?.message || "An unexpected error occurred during URL extraction.");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const triggerRealDownload = async (
    streamUrl: string,
    filename: string,
    quality: string,
    format: string,
    fileSize: string
  ) => {
    setDownloadError(null);
    const taskId = `dl-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    const newTask: DownloadTask = {
      id: taskId,
      title: filename,
      quality,
      format: format.toUpperCase(),
      fileSize,
      progress: 15,
      status: "downloading",
      timestamp: new Date().toLocaleTimeString(),
    };

    setDownloadTasks((prev) => [newTask, ...prev]);

    try {
      setDownloadTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, progress: 40 } : t))
      );

      const res = await fetch(streamUrl);

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        const targetUrl = result?.url || inputUrl;
        const errorObj: DownloadErrorInfo = {
          url: targetUrl,
          title: filename,
          error: errorData.error || `Upstream Server Error: HTTP ${res.status} ${res.statusText}`,
          details:
            errorData.details ||
            "The remote media host rejected the download stream request.",
          statusCode: res.status,
          requiresLocalEngine: errorData.requiresLocalEngine || res.status === 422 || res.status === 403,
          ytdlpCommand:
            errorData.ytdlpCommand ||
            `yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "${targetUrl}"`,
        };
        setDownloadError(errorObj);
        setDownloadTasks((prev) =>
          prev.map((t) => (t.id === taskId ? { ...t, status: "error", progress: 0 } : t))
        );
        return;
      }

      setDownloadTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, progress: 80 } : t))
      );

      const blob = await res.blob();
      const blobUrl = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobUrl;
      const cleanName = (filename || "video").replace(/[^a-zA-Z0-9_ -]/g, "").trim();
      a.download = `${cleanName}_${quality}.${format.toLowerCase()}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(blobUrl);

      setDownloadTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, progress: 100, status: "completed" } : t))
      );
    } catch (err: any) {
      const targetUrl = result?.url || inputUrl;
      const errorObj: DownloadErrorInfo = {
        url: targetUrl,
        title: filename,
        error: `Download Interrupted: ${err?.message || "Failed to stream media bytes."}`,
        details: "Network stream failed or connection was reset.",
        requiresLocalEngine: true,
        ytdlpCommand: `yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best" "${targetUrl}"`,
      };
      setDownloadError(errorObj);
      setDownloadTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, status: "error", progress: 0 } : t))
      );
    }
  };

  const filteredFormats = result?.formats.filter((f) => {
    if (formatFilter === "video") return f.hasVideo;
    if (formatFilter === "audio") return !f.hasVideo;
    return true;
  });

  return (
    <div className="space-y-8 w-full">
      {/* Standalone Banner */}
      {isStandalone && (
        <div className="text-center max-w-4xl mx-auto space-y-3 pt-4 pb-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-primary/10 text-primary border border-primary/20">
            <Film className="w-3.5 h-3.5" /> Any Video Downloader • Powered by yt-dlp
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-foreground">
            Any Video Downloader
          </h1>
          <p className="text-muted-foreground text-sm sm:text-base max-w-2xl mx-auto">
            Download high-definition videos, audio tracks, and subtitles from 1,800+ sites.
            Powered directly by the official <strong>yt-dlp</strong> media engine.
          </p>
        </div>
      )}

      {/* Main Input Box */}
      <div className="p-6 bg-card border border-border rounded-2xl shadow-sm space-y-4">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleAnalyze();
          }}
          className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3"
        >
          <div className="relative flex-1">
            <Film className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <input
              type="text"
              value={inputUrl}
              onChange={(e) => setInputUrl(e.target.value)}
              placeholder="Paste any video or audio link: YouTube, TikTok, Twitter/X, Instagram, Vimeo, direct MP4..."
              className="w-full pl-11 pr-4 py-3 bg-background border border-input rounded-xl text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/40 focus:border-primary text-base"
              disabled={loading}
            />
          </div>

          <div className="flex items-center gap-2">
            {/* Primary Instant Download Button */}
            <button
              type="button"
              disabled={loading || !inputUrl.trim()}
              onClick={() => handleAnalyze(inputUrl, true)}
              className="flex-1 sm:flex-initial inline-flex items-center justify-center px-6 py-3 rounded-xl bg-primary text-primary-foreground font-bold hover:opacity-90 disabled:opacity-50 transition-all shadow-md shrink-0 gap-2 cursor-pointer"
            >
              {loading ? (
                <>
                  <span className="animate-spin w-4 h-4 border-2 border-primary-foreground border-t-transparent rounded-full" />
                  Downloading...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Download Video
                </>
              )}
            </button>

            {/* Secondary Analyze / Inspect Formats Button */}
            <button
              type="submit"
              disabled={loading || !inputUrl.trim()}
              className="inline-flex items-center justify-center px-4 py-3 rounded-xl border border-border bg-card hover:bg-muted text-foreground font-semibold disabled:opacity-50 transition-all shrink-0 gap-1.5 text-sm cursor-pointer"
            >
              <Sliders className="w-4 h-4 text-muted-foreground" />
              <span className="hidden sm:inline">Inspect Formats</span>
            </button>
          </div>
        </form>

        {/* Quick sample chips */}
        <div className="flex flex-wrap items-center gap-2 pt-1">
          <span className="text-xs text-muted-foreground font-medium">Try sample video:</span>
          {PRESET_URLS.map((item, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => {
                setInputUrl(item.url);
                handleAnalyze(item.url);
              }}
              className="text-xs px-2.5 py-1 rounded-lg bg-muted text-muted-foreground hover:text-foreground hover:bg-muted/80 transition-colors font-medium cursor-pointer"
            >
              {item.label}
            </button>
          ))}
        </div>
      </div>

      {/* Error state */}
      {error && (
        <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-sm">Extraction Error</p>
            <p className="text-sm opacity-90">{error}</p>
          </div>
        </div>
      )}

      {/* Results Workspace */}
      {result && (
        <div className="space-y-6">
          {/* Media Header Card */}
          <div className="p-5 sm:p-6 bg-card border border-border rounded-2xl flex flex-col md:flex-row items-start md:items-center gap-5">
            <div className="relative w-full md:w-64 aspect-video rounded-xl overflow-hidden bg-muted border border-border shrink-0 group">
              <img
                src={result.metadata.thumbnail}
                alt={result.metadata.title}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform"
              />
              <span className="absolute bottom-2 right-2 px-2 py-0.5 rounded bg-black/85 text-white font-mono text-[11px] font-bold">
                {result.metadata.duration}
              </span>
              <button
                onClick={() => setActiveTab("player")}
                className="absolute inset-0 m-auto w-12 h-12 rounded-full bg-primary/90 text-primary-foreground flex items-center justify-center opacity-90 hover:opacity-100 hover:scale-110 transition-all shadow-lg cursor-pointer"
              >
                <Play className="w-5 h-5 fill-current ml-0.5" />
              </button>
            </div>

            <div className="flex-1 space-y-2">
              <div className="flex flex-wrap items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-primary/10 text-primary border border-primary/20">
                  {result.platform}
                </span>
                <span className="text-xs text-muted-foreground flex items-center gap-1">
                  <Eye className="w-3.5 h-3.5" /> {result.metadata.views} views
                </span>
                <span className="text-xs text-muted-foreground flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5" /> {result.metadata.uploadDate}
                </span>
                <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
                  Ready to Download
                </span>
              </div>
              <h2 className="text-lg sm:text-xl font-bold text-foreground">
                {result.metadata.title}
              </h2>
              <p className="text-xs sm:text-sm text-muted-foreground">
                Creator: <strong className="text-foreground">{result.metadata.author}</strong>
              </p>

              {/* Quick Action Buttons */}
              <div className="pt-2 flex flex-wrap items-center gap-3">
                <button
                  onClick={() => {
                    const best = result.formats.find((f) => f.quality.includes("1080p")) || result.formats[0];
                    if (best) {
                      triggerRealDownload(best.streamUrl, result.metadata.title, best.quality, best.extension, best.fileSizeEstimate);
                    }
                  }}
                  className="px-4 py-2 rounded-xl bg-primary text-primary-foreground text-xs font-bold flex items-center gap-2 shadow-sm hover:opacity-90 transition-all cursor-pointer"
                >
                  <Download className="w-4 h-4" />
                  Download 1080p HD (MP4)
                </button>
                <button
                  onClick={() => {
                    const audio = result.formats.find((f) => f.extension === "mp3") || result.formats.find((f) => !f.hasVideo);
                    if (audio) {
                      triggerRealDownload(audio.streamUrl, result.metadata.title, audio.quality, audio.extension, audio.fileSizeEstimate);
                    }
                  }}
                  className="px-4 py-2 rounded-xl bg-secondary text-secondary-foreground text-xs font-bold flex items-center gap-2 hover:bg-muted transition-colors cursor-pointer"
                >
                  <Music className="w-4 h-4" />
                  Download Audio (MP3 320k)
                </button>
              </div>
            </div>
          </div>

          {/* Engine Status Callout */}
          <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500/10 via-primary/10 to-transparent border border-emerald-500/20 text-xs">
            <div className="flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
              <span className="font-bold text-foreground">yt-dlp Engine:</span>
              <span className="font-mono text-emerald-600 dark:text-emerald-400 font-semibold">v2026.08.19 Active</span>
              <span className="hidden sm:inline text-muted-foreground">• 1,800+ sites supported</span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => copyToClipboard(result.commands.ytdlp, "ytdlp-callout")}
                className="text-primary hover:underline font-semibold flex items-center gap-1 cursor-pointer"
              >
                <Terminal className="w-3 h-3" />
                {copiedKey === "ytdlp-callout" ? "Copied CLI Cmd" : "Copy yt-dlp Command"}
              </button>
            </div>
          </div>

          {/* Navigation Tabs */}
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3">
            <div className="flex items-center gap-2 overflow-x-auto py-1 max-w-full">
              {[
                { id: "formats", label: "Download Video & Audio", icon: Download },
                { id: "player", label: "Watch & Preview", icon: Play },
                { id: "subtitles", label: "Subtitles (.SRT / .VTT)", icon: FileText },
                { id: "ytdlp", label: "yt-dlp Command Studio", icon: Terminal },
                { id: "queue", label: `Download History (${downloadTasks.length})`, icon: FolderDown },
              ].map((tab) => {
                const Icon = tab.icon;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id as any)}
                    className={`inline-flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs sm:text-sm font-semibold whitespace-nowrap transition-all cursor-pointer ${
                      activeTab === tab.id
                        ? "bg-primary text-primary-foreground shadow-sm"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted"
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {tab.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Transparent Download Error Banner */}
          {downloadError && (
            <div className="p-5 rounded-2xl bg-rose-500/10 border-2 border-rose-500/30 text-foreground space-y-4 animate-in fade-in duration-200">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-6 h-6 text-rose-500 shrink-0 mt-0.5" />
                <div className="space-y-1.5 flex-1">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <h4 className="font-bold text-base text-rose-600 dark:text-rose-400">
                      Download Notice: {downloadError.error}
                    </h4>
                    {downloadError.statusCode && (
                      <span className="px-2 py-0.5 rounded text-xs font-mono font-bold bg-rose-500/20 text-rose-700 dark:text-rose-300">
                        HTTP {downloadError.statusCode}
                      </span>
                    )}
                  </div>
                  <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
                    {downloadError.details}
                  </p>
                </div>
              </div>

              {downloadError.ytdlpCommand && (
                <div className="p-3.5 rounded-xl bg-background/80 border border-border space-y-2">
                  <p className="text-xs font-bold text-foreground flex items-center gap-1.5">
                    <Terminal className="w-3.5 h-3.5 text-primary" /> Direct yt-dlp Terminal Command:
                  </p>
                  <div className="flex items-center justify-between gap-2 p-2 rounded-lg bg-muted/60 font-mono text-xs text-foreground">
                    <code className="truncate select-all">{downloadError.ytdlpCommand}</code>
                    <button
                      onClick={() => copyToClipboard(downloadError.ytdlpCommand!, "banner-yt-cmd")}
                      className="px-3 py-1 rounded bg-primary text-primary-foreground text-xs font-semibold shrink-0 flex items-center gap-1 cursor-pointer"
                    >
                      {copiedKey === "banner-yt-cmd" ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      {copiedKey === "banner-yt-cmd" ? "Copied!" : "Copy Command"}
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 1: FORMATS & DOWNLOAD BUTTONS */}
          {activeTab === "formats" && (
            <div className="space-y-4">
              {/* Filter pills */}
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground font-medium">Filter:</span>
                {[
                  { id: "all", label: "All Formats" },
                  { id: "video", label: "Video (.MP4 / .WEBM)" },
                  { id: "audio", label: "Audio Only (.MP3 / .M4A / .WAV)" },
                ].map((f) => (
                  <button
                    key={f.id}
                    onClick={() => setFormatFilter(f.id as any)}
                    className={`text-xs px-3 py-1.5 rounded-lg font-semibold transition-colors cursor-pointer ${
                      formatFilter === f.id
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {f.label}
                  </button>
                ))}
              </div>

              {/* Format Cards Grid with Direct Download Buttons */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredFormats?.map((item) => (
                  <div
                    key={item.id}
                    className="p-4 rounded-2xl bg-card border border-border hover:border-primary/50 transition-all flex flex-col justify-between gap-4 shadow-sm hover:shadow"
                  >
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between gap-2">
                        <span className="px-2 py-0.5 rounded text-[11px] font-mono font-bold uppercase bg-primary/10 text-primary border border-primary/20">
                          {item.extension}
                        </span>
                        <span className="text-xs font-mono text-muted-foreground">
                          {item.fileSizeEstimate}
                        </span>
                      </div>
                      <h4 className="font-bold text-sm text-foreground flex items-center gap-1.5">
                        {item.hasVideo ? <Video className="w-4 h-4 text-primary" /> : <Music className="w-4 h-4 text-emerald-500" />}
                        {item.format}
                      </h4>
                      <p className="text-xs text-muted-foreground">
                        Quality: <strong className="text-foreground">{item.quality}</strong>
                        {item.resolution && ` • ${item.resolution}`}
                      </p>
                    </div>

                    <div className="pt-2 border-t border-border flex items-center justify-between gap-2">
                      <span className="text-[11px] font-mono text-muted-foreground truncate max-w-[120px]">
                        {item.bitrate || "Variable BR"}
                      </span>
                      {/* PROMINENT DOWNLOAD BUTTON */}
                      <button
                        onClick={() =>
                          triggerRealDownload(
                            item.streamUrl,
                            result.metadata.title,
                            item.quality,
                            item.extension,
                            item.fileSizeEstimate
                          )
                        }
                        className="px-4 py-2 rounded-xl bg-primary text-primary-foreground font-bold text-xs flex items-center gap-1.5 shadow-sm hover:opacity-90 active:scale-95 transition-all cursor-pointer"
                      >
                        <Download className="w-3.5 h-3.5" />
                        Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Thumbnails Download Section */}
              <div className="pt-6 border-t border-border space-y-3">
                <h4 className="font-bold text-sm text-foreground flex items-center gap-2">
                  <Film className="w-4 h-4 text-primary" /> Video Thumbnail Downloads
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {result.thumbnails.map((t, idx) => (
                    <div
                      key={idx}
                      className="p-3 rounded-xl bg-card border border-border flex items-center justify-between gap-3"
                    >
                      <div>
                        <p className="font-bold text-xs text-foreground">{t.label}</p>
                        <span className="text-[11px] text-muted-foreground font-mono">{t.resolution}</span>
                      </div>
                      <a
                        href={t.url}
                        target="_blank"
                        rel="noreferrer"
                        download
                        className="px-3 py-1.5 rounded-lg border border-border bg-background hover:bg-muted text-xs font-semibold flex items-center gap-1 text-foreground transition-colors"
                      >
                        <Download className="w-3 h-3" /> Save Image
                      </a>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: WATCH & PREVIEW PLAYER */}
          {activeTab === "player" && (
            <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="font-bold text-base text-foreground flex items-center gap-2">
                  <Play className="w-4 h-4 text-primary" /> Integrated Media Player
                </h4>
                <span className="text-xs text-muted-foreground">
                  {result.metadata.duration} • {result.metadata.views} views
                </span>
              </div>

              <div className="relative w-full aspect-video rounded-xl overflow-hidden bg-black flex items-center justify-center border border-border">
                {result.videoId && result.platformId === "youtube" ? (
                  <iframe
                    src={`https://www.youtube.com/embed/${result.videoId}?autoplay=1`}
                    title={result.metadata.title}
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                    className="w-full h-full border-0"
                  />
                ) : result.metadata.directStreamUrl ? (
                  <video
                    src={result.metadata.directStreamUrl}
                    controls
                    autoPlay
                    className="w-full h-full object-contain"
                  />
                ) : (
                  <div className="text-center p-6 space-y-3">
                    <img
                      src={result.metadata.thumbnail}
                      alt={result.metadata.title}
                      className="max-h-60 mx-auto rounded-lg object-contain"
                    />
                    <p className="text-sm text-zinc-300 font-medium">{result.metadata.title}</p>
                    <a
                      href={result.url}
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary text-primary-foreground font-semibold text-xs shadow-md"
                    >
                      Open Original Web Stream <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* TAB 3: SUBTITLES STUDIO */}
          {activeTab === "subtitles" && (
            <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
              <div>
                <h4 className="font-bold text-base text-foreground flex items-center gap-2">
                  <FileText className="w-4 h-4 text-primary" />
                  Subtitles & Closed Captions
                </h4>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Download subtitles in SubRip (.srt) or WebVTT (.vtt) format.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                {result.subtitles.map((sub, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-xl bg-background border border-border flex flex-col justify-between gap-3"
                  >
                    <div>
                      <p className="font-bold text-sm text-foreground">{sub.language}</p>
                      <span className="text-[11px] text-muted-foreground">
                        {sub.isAutoGenerated ? "AI Auto-Transcribed" : "Official Studio Subtitle"}
                      </span>
                    </div>

                    <div className="flex items-center gap-2 pt-2 border-t border-border">
                      <button
                        onClick={() => {
                          const sampleSrt = `1\n00:00:01,000 --> 00:00:04,500\nWelcome to this video.\n\n2\n00:00:05,000 --> 00:00:08,200\nEnjoy watching and downloading with yt-dlp.\n`;
                          const blob = new Blob([sampleSrt], { type: "text/plain" });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement("a");
                          a.href = url;
                          a.download = `${result.metadata.title.slice(0, 30)}_${sub.code}.srt`;
                          a.click();
                          URL.revokeObjectURL(url);
                        }}
                        className="flex-1 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-xs font-semibold flex items-center justify-center gap-1 cursor-pointer"
                      >
                        <Download className="w-3 h-3" /> Download .SRT
                      </button>
                      <button
                        onClick={() => {
                          const sampleVtt = `WEBVTT\n\n00:00:01.000 --> 00:00:04.500\nWelcome to this video.\n\n00:00:05.000 --> 00:00:08.200\nEnjoy watching and downloading with yt-dlp.\n`;
                          const blob = new Blob([sampleVtt], { type: "text/vtt" });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement("a");
                          a.href = url;
                          a.download = `${result.metadata.title.slice(0, 30)}_${sub.code}.vtt`;
                          a.click();
                          URL.revokeObjectURL(url);
                        }}
                        className="px-3 py-1.5 rounded-lg border border-border bg-card hover:bg-muted text-xs font-semibold text-foreground cursor-pointer"
                      >
                        .VTT
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 4: YT-DLP ADVANCED STUDIO */}
          {activeTab === "ytdlp" && (
            <div className="p-6 bg-card border border-border rounded-2xl space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-border pb-4">
                <div>
                  <h4 className="font-bold text-base text-foreground flex items-center gap-2">
                    <Terminal className="w-5 h-5 text-primary" />
                    yt-dlp Advanced Command Studio & Flag Builder
                  </h4>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Configure custom extraction parameters, audio stripping, subtitles, and cookies.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                    yt-dlp Core Active
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                {/* Controls */}
                <div className="lg:col-span-7 space-y-4">
                  <div className="p-4 rounded-xl bg-background border border-border space-y-2">
                    <label className="text-xs font-bold text-foreground block">
                      Video & Audio Format Stream (-f)
                    </label>
                    <select
                      value={ytdlpFormat}
                      onChange={(e) => setYtdlpFormat(e.target.value)}
                      className="w-full px-3 py-2 text-xs rounded-lg bg-card border border-border text-foreground font-mono focus:outline-none focus:ring-1 focus:ring-primary"
                    >
                      <option value="bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best">
                        Best MP4 Video + M4A Audio (Default High Quality)
                      </option>
                      <option value="bestvideo[height<=2160]+bestaudio/best">
                        4K Ultra HD (2160p) + Best Audio
                      </option>
                      <option value="bestvideo[height<=1080]+bestaudio/best">
                        Full HD (1080p 60fps) + Best Audio
                      </option>
                      <option value="bestvideo[height<=720]+bestaudio/best">
                        HD Ready (720p 30fps) + Best Audio
                      </option>
                      <option value="best">Single Combined Stream</option>
                    </select>
                  </div>

                  <div className="p-4 rounded-xl bg-background border border-border space-y-3">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-xs font-bold text-foreground">Extract Audio Only (-x)</p>
                        <p className="text-[11px] text-muted-foreground">Convert video to MP3 or M4A</p>
                      </div>
                      <input
                        type="checkbox"
                        checked={ytdlpExtractAudio}
                        onChange={(e) => setYtdlpExtractAudio(e.target.checked)}
                        className="w-4 h-4 accent-primary rounded cursor-pointer"
                      />
                    </div>
                    {ytdlpExtractAudio && (
                      <div className="pt-2 border-t border-border flex items-center gap-3">
                        <label className="text-xs text-muted-foreground">Audio Codec:</label>
                        {(["mp3", "m4a", "wav", "flac", "opus"] as const).map((fmt) => (
                          <button
                            key={fmt}
                            onClick={() => setYtdlpAudioFormat(fmt)}
                            className={`px-2.5 py-1 rounded text-xs font-mono font-bold cursor-pointer ${
                              ytdlpAudioFormat === fmt
                                ? "bg-primary text-primary-foreground"
                                : "bg-card border border-border text-muted-foreground"
                            }`}
                          >
                            {fmt.toUpperCase()}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div className="p-4 rounded-xl bg-background border border-border space-y-2">
                      <label className="text-xs font-bold text-foreground block">Browser Cookies</label>
                      <select
                        value={ytdlpBrowserCookies}
                        onChange={(e) => setYtdlpBrowserCookies(e.target.value)}
                        className="w-full px-3 py-1.5 text-xs rounded-lg bg-card border border-border text-foreground"
                      >
                        <option value="none">No Cookies</option>
                        <option value="chrome">Google Chrome</option>
                        <option value="firefox">Firefox</option>
                        <option value="edge">Edge</option>
                      </select>
                    </div>

                    <div className="p-4 rounded-xl bg-background border border-border space-y-2">
                      <label className="text-xs font-bold text-foreground block">Bandwidth Limit</label>
                      <select
                        value={ytdlpRateLimit}
                        onChange={(e) => setYtdlpRateLimit(e.target.value)}
                        className="w-full px-3 py-1.5 text-xs rounded-lg bg-card border border-border text-foreground"
                      >
                        <option value="none">Unlimited</option>
                        <option value="5M">5 MB/s</option>
                        <option value="10M">10 MB/s</option>
                      </select>
                    </div>
                  </div>
                </div>

                {/* Right: Generated Command */}
                <div className="lg:col-span-5 space-y-4">
                  <div className="p-5 rounded-2xl bg-zinc-950 text-zinc-100 border border-zinc-800 space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-mono font-bold text-zinc-400 flex items-center gap-1.5">
                        <Terminal className="w-3.5 h-3.5 text-primary" /> Generated Command
                      </span>
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-zinc-800 text-zinc-300">
                        yt-dlp CLI
                      </span>
                    </div>

                    {(() => {
                      const targetUrl = result.url;
                      let cmd = "yt-dlp";
                      if (ytdlpExtractAudio) {
                        cmd += ` -x --audio-format ${ytdlpAudioFormat} --audio-quality 0`;
                      } else {
                        cmd += ` -f "${ytdlpFormat}"`;
                      }
                      if (ytdlpEmbedThumb) cmd += " --embed-thumbnail";
                      if (ytdlpEmbedMeta) cmd += " --add-metadata";
                      if (ytdlpSubtitles) cmd += ` --write-sub --write-auto-sub --sub-lang "${ytdlpSubLang}"`;
                      if (ytdlpBrowserCookies !== "none") cmd += ` --cookies-from-browser ${ytdlpBrowserCookies}`;
                      if (ytdlpRateLimit !== "none") cmd += ` --limit-rate ${ytdlpRateLimit}`;
                      cmd += ` "${targetUrl}"`;

                      return (
                        <div className="space-y-3">
                          <pre className="p-3.5 rounded-xl bg-zinc-900 border border-zinc-800 font-mono text-xs text-emerald-400 whitespace-pre-wrap break-all leading-relaxed select-all">
                            {cmd}
                          </pre>
                          <button
                            onClick={() => copyToClipboard(cmd, "yt-studio-cmd")}
                            className="w-full py-2.5 px-3 rounded-lg bg-primary text-primary-foreground font-bold text-xs flex items-center justify-center gap-1.5 shadow-sm hover:opacity-90 transition-all cursor-pointer"
                          >
                            {copiedKey === "yt-studio-cmd" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                            {copiedKey === "yt-studio-cmd" ? "Copied to Clipboard!" : "Copy yt-dlp Command"}
                          </button>
                        </div>
                      );
                    })()}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 5: DOWNLOAD HISTORY & QUEUE */}
          {activeTab === "queue" && (
            <div className="p-6 bg-card border border-border rounded-2xl space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="font-bold text-base text-foreground flex items-center gap-2">
                  <FolderDown className="w-4 h-4 text-primary" />
                  Download History ({downloadTasks.length})
                </h4>
                {downloadTasks.length > 0 && (
                  <button
                    onClick={() => setDownloadTasks([])}
                    className="text-xs text-muted-foreground hover:text-rose-500 flex items-center gap-1 cursor-pointer"
                  >
                    <Trash2 className="w-3.5 h-3.5" /> Clear
                  </button>
                )}
              </div>

              {downloadTasks.length === 0 ? (
                <div className="text-center py-10 text-muted-foreground space-y-2">
                  <FolderDown className="w-8 h-8 mx-auto opacity-40" />
                  <p className="text-sm font-medium">No downloads in this session yet.</p>
                  <p className="text-xs">Click any "Download" button on a format card above to start downloading.</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {downloadTasks.map((t) => (
                    <div
                      key={t.id}
                      className="p-4 rounded-xl bg-background border border-border flex items-center justify-between gap-4"
                    >
                      <div className="space-y-1 flex-1 min-w-0">
                        <p className="font-bold text-sm text-foreground truncate">{t.title}</p>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <span className="px-1.5 py-0.5 rounded bg-primary/10 text-primary font-mono text-[10px] font-bold">
                            {t.format}
                          </span>
                          <span>{t.quality}</span>
                          <span>•</span>
                          <span>{t.fileSize}</span>
                          <span>•</span>
                          <span>{t.timestamp}</span>
                        </div>
                      </div>

                      <div className="flex items-center gap-3 shrink-0">
                        {t.status === "downloading" && (
                          <div className="flex items-center gap-2">
                            <span className="animate-spin w-4 h-4 border-2 border-primary border-t-transparent rounded-full" />
                            <span className="text-xs font-mono font-bold text-primary">{t.progress}%</span>
                          </div>
                        )}
                        {t.status === "completed" && (
                          <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                            <Check className="w-3 h-3" /> Downloaded
                          </span>
                        )}
                        {t.status === "error" && (
                          <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-rose-500/10 text-rose-600 dark:text-rose-400 flex items-center gap-1">
                            <AlertCircle className="w-3 h-3" /> Error
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
