import { FormatDefinition } from "./types";

export const FORMAT_REGISTRY: Record<string, FormatDefinition> = {
  // ===================
  // IMAGES
  // ===================
  jpg: {
    id: "jpg",
    category: "image",
    displayName: "JPEG Image",
    extensions: ["jpg", "jpeg"],
    mimeTypes: ["image/jpeg"],
    aliases: ["jpeg"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      quality: true,
      width: true,
      height: true,
      backgroundColor: true,
      grayscale: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "jpg",
    description: "Standard lossy compressed image format widely used on the web and digital cameras.",
  },
  png: {
    id: "png",
    category: "image",
    displayName: "PNG Image",
    extensions: ["png"],
    mimeTypes: ["image/png"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      width: true,
      height: true,
      grayscale: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "png",
    description: "Lossless raster image format supporting alpha channel transparency.",
  },
  webp: {
    id: "webp",
    category: "image",
    displayName: "WebP Image",
    extensions: ["webp"],
    mimeTypes: ["image/webp"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      quality: true,
      width: true,
      height: true,
      grayscale: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "webp",
    description: "Modern image format developed by Google providing superior lossy and lossless compression for web graphics.",
  },
  avif: {
    id: "avif",
    category: "image",
    displayName: "AVIF Image",
    extensions: ["avif"],
    mimeTypes: ["image/avif"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      quality: true,
      width: true,
      height: true,
    },
    preview: true,
    compression: true,
    metadata: false,
    seoSlug: "avif",
    description: "Next-generation image compression format based on the AV1 video codec offering ultra-high efficiency.",
  },
  bmp: {
    id: "bmp",
    category: "image",
    displayName: "Bitmap Image",
    extensions: ["bmp"],
    mimeTypes: ["image/bmp", "image/x-bmp"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      width: true,
      height: true,
      grayscale: true,
    },
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "bmp",
    description: "Uncompressed bitmap graphics format used predominantly in Windows environments.",
  },
  ico: {
    id: "ico",
    category: "image",
    displayName: "ICO Favicon",
    extensions: ["ico"],
    mimeTypes: ["image/x-icon", "image/vnd.microsoft.icon"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    supportedOptions: {
      width: true,
      height: true,
    },
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "ico",
    description: "Icon format used by web browsers for website favicons and Windows desktop shortcuts.",
  },
  svg: {
    id: "svg",
    category: "vector",
    displayName: "Scalable Vector Graphics",
    extensions: ["svg"],
    mimeTypes: ["image/svg+xml"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "xml"],
    supportedOptions: {
      width: true,
      height: true,
    },
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "svg",
    description: "XML-based two-dimensional vector image format with interactive and dynamic capabilities.",
  },
  gif: {
    id: "gif",
    category: "image",
    displayName: "GIF Animation/Image",
    extensions: ["gif"],
    mimeTypes: ["image/gif"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "media"],
    supportedOptions: {
      fps: true,
      width: true,
      height: true,
    },
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "gif",
    description: "8-bit palette bitmap format supporting simple animations and transparency.",
  },
  tiff: {
    id: "tiff",
    category: "image",
    displayName: "TIFF Image",
    extensions: ["tiff", "tif"],
    mimeTypes: ["image/tiff"],
    aliases: ["tif"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "browser",
    engines: ["canvas"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "tiff",
    description: "High-quality raster image format favored in commercial publishing and scientific imaging.",
  },
  heic: {
    id: "heic",
    category: "image",
    displayName: "HEIC Image",
    extensions: ["heic", "heif"],
    mimeTypes: ["image/heic", "image/heif"],
    aliases: ["heif"],
    canInput: true,
    canOutput: false,
    status: "COMING_SOON",
    processingMode: "server",
    engines: ["libheif"],
    preview: false,
    compression: false,
    metadata: true,
    seoSlug: "heic",
    description: "High Efficiency Image Container format used by modern Apple iOS devices.",
  },
  psd: {
    id: "psd",
    category: "image",
    displayName: "Adobe Photoshop Document",
    extensions: ["psd"],
    mimeTypes: ["image/vnd.adobe.photoshop"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["canvas", "browser"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "psd",
    description: "Layered graphics file format native to Adobe Photoshop.",
  },

  // ===================
  // DOCUMENTS
  // ===================
  pdf: {
    id: "pdf",
    category: "document",
    displayName: "PDF Document",
    extensions: ["pdf"],
    mimeTypes: ["application/pdf"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["pdf-lib", "pdfjs-dist"],
    supportedOptions: {
      pageSize: true,
      orientation: true,
      margins: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "pdf",
    description: "Universal document format by Adobe preserving layout, vector artwork, and typography across all devices.",
  },
  txt: {
    id: "txt",
    category: "document",
    displayName: "Plain Text Document",
    extensions: ["txt", "text"],
    mimeTypes: ["text/plain"],
    aliases: ["text"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["text"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "txt",
    description: "Unformatted plain ASCII or UTF-8 text file compatible with any editor.",
  },
  md: {
    id: "md",
    category: "document",
    displayName: "Markdown Document",
    extensions: ["md", "markdown"],
    mimeTypes: ["text/markdown", "text/x-markdown"],
    aliases: ["markdown"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["markdown"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "markdown",
    description: "Lightweight markup language with plain text formatting syntax designed for readability.",
  },
  html: {
    id: "html",
    category: "document",
    displayName: "HTML Web Page",
    extensions: ["html", "htm"],
    mimeTypes: ["text/html"],
    aliases: ["htm"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["dom"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "html",
    description: "Standard HyperText Markup Language format used to build and present content on the World Wide Web.",
  },
  docx: {
    id: "docx",
    category: "document",
    displayName: "Microsoft Word Document",
    extensions: ["docx"],
    mimeTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip", "xml"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "docx",
    description: "XML-based document format for Microsoft Word 2007 and newer.",
  },
  doc: {
    id: "doc",
    category: "document",
    displayName: "Microsoft Word 97-2003 Document",
    extensions: ["doc"],
    mimeTypes: ["application/msword"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "browser",
    engines: ["text"],
    preview: false,
    compression: false,
    metadata: true,
    seoSlug: "doc",
    description: "Legacy binary word processing format for Microsoft Word versions up to 2003.",
  },
  odt: {
    id: "odt",
    category: "document",
    displayName: "OpenDocument Text",
    extensions: ["odt"],
    mimeTypes: ["application/vnd.oasis.opendocument.text"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip", "xml"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "odt",
    description: "Open standard word processing document format used by LibreOffice and OpenOffice.",
  },
  rtf: {
    id: "rtf",
    category: "document",
    displayName: "Rich Text Format",
    extensions: ["rtf"],
    mimeTypes: ["application/rtf", "text/rtf"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["text"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "rtf",
    description: "Cross-platform formatted text format developed by Microsoft.",
  },

  // ===================
  // AUDIO
  // ===================
  wav: {
    id: "wav",
    category: "audio",
    displayName: "WAV Audio",
    extensions: ["wav"],
    mimeTypes: ["audio/wav", "audio/x-wav"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio"],
    supportedOptions: {
      sampleRate: true,
      channels: true,
      volume: true,
      trim: true,
    },
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "wav",
    description: "Uncompressed PCM audio container standard developed by Microsoft and IBM.",
  },
  mp3: {
    id: "mp3",
    category: "audio",
    displayName: "MP3 Audio",
    extensions: ["mp3"],
    mimeTypes: ["audio/mpeg", "audio/mp3"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio", "lamejs"],
    supportedOptions: {
      bitrate: true,
      sampleRate: true,
      channels: true,
      volume: true,
      trim: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "mp3",
    description: "Universally supported lossy audio format with robust file size compression.",
  },
  ogg: {
    id: "ogg",
    category: "audio",
    displayName: "OGG Vorbis Audio",
    extensions: ["ogg", "oga"],
    mimeTypes: ["audio/ogg"],
    aliases: ["oga"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio"],
    supportedOptions: {
      sampleRate: true,
      channels: true,
      volume: true,
      trim: true,
    },
    preview: true,
    compression: true,
    metadata: false,
    seoSlug: "ogg",
    description: "Open-source, patent-free lossy audio compression format.",
  },
  flac: {
    id: "flac",
    category: "audio",
    displayName: "FLAC Lossless Audio",
    extensions: ["flac"],
    mimeTypes: ["audio/flac"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio"],
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "flac",
    description: "Free Lossless Audio Codec preserving bit-perfect audio reproduction.",
  },
  aac: {
    id: "aac",
    category: "audio",
    displayName: "AAC Audio",
    extensions: ["aac"],
    mimeTypes: ["audio/aac"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio"],
    preview: true,
    compression: true,
    metadata: false,
    seoSlug: "aac",
    description: "Advanced Audio Coding standard offering higher sound quality than MP3 at similar bitrates.",
  },
  m4a: {
    id: "m4a",
    category: "audio",
    displayName: "M4A Audio",
    extensions: ["m4a"],
    mimeTypes: ["audio/mp4", "audio/x-m4a"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["webaudio"],
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "m4a",
    description: "MPEG-4 audio container commonly used in Apple iTunes and iPhone voice memos.",
  },

  // ===================
  // VIDEO
  // ===================
  mp4: {
    id: "mp4",
    category: "video",
    displayName: "MP4 Video",
    extensions: ["mp4", "m4v"],
    mimeTypes: ["video/mp4"],
    aliases: ["m4v"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["media", "canvas"],
    supportedOptions: {
      fps: true,
      width: true,
      height: true,
      trim: true,
    },
    preview: true,
    compression: true,
    metadata: true,
    seoSlug: "mp4",
    description: "The most widely supported digital multimedia container format for video and audio.",
  },
  webm: {
    id: "webm",
    category: "video",
    displayName: "WebM Video",
    extensions: ["webm"],
    mimeTypes: ["video/webm"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["media", "canvas"],
    supportedOptions: {
      fps: true,
      width: true,
      height: true,
      trim: true,
    },
    preview: true,
    compression: true,
    metadata: false,
    seoSlug: "webm",
    description: "Royalty-free open media file format designed specifically for the HTML5 web.",
  },
  mov: {
    id: "mov",
    category: "video",
    displayName: "QuickTime MOV Video",
    extensions: ["mov"],
    mimeTypes: ["video/quicktime"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["media", "canvas"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "mov",
    description: "Apple QuickTime movie container format widely used in video editing.",
  },
  avi: {
    id: "avi",
    category: "video",
    displayName: "AVI Video",
    extensions: ["avi"],
    mimeTypes: ["video/x-msvideo"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "server",
    engines: ["ffmpeg"],
    preview: false,
    compression: false,
    metadata: false,
    seoSlug: "avi",
    description: "Audio Video Interleave multimedia container format introduced by Microsoft.",
  },
  mkv: {
    id: "mkv",
    category: "video",
    displayName: "Matroska Video",
    extensions: ["mkv"],
    mimeTypes: ["video/x-matroska"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "server",
    engines: ["ffmpeg"],
    preview: false,
    compression: false,
    metadata: false,
    seoSlug: "mkv",
    description: "Extensible open-standard multimedia container holding unlimited video, audio, and subtitle tracks.",
  },

  // ===================
  // DATA & SPREADSHEETS
  // ===================
  csv: {
    id: "csv",
    category: "spreadsheet",
    displayName: "CSV Spreadsheet Data",
    extensions: ["csv"],
    mimeTypes: ["text/csv", "application/csv"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["data"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "csv",
    description: "Comma-Separated Values tabular data format readable by spreadsheet and database systems.",
  },
  tsv: {
    id: "tsv",
    category: "spreadsheet",
    displayName: "TSV Tab-Separated Data",
    extensions: ["tsv"],
    mimeTypes: ["text/tab-separated-values"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["data"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "tsv",
    description: "Tab-Separated Values text format used for data analysis and bio-informatics tables.",
  },
  json: {
    id: "json",
    category: "data",
    displayName: "JSON Data Interchange",
    extensions: ["json"],
    mimeTypes: ["application/json", "text/json"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["data"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "json",
    description: "Standard JavaScript Object Notation format used for APIs and structured datasets.",
  },
  xlsx: {
    id: "xlsx",
    category: "spreadsheet",
    displayName: "Microsoft Excel Workbook",
    extensions: ["xlsx"],
    mimeTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip", "xml"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "xlsx",
    description: "XML-based spreadsheet file format native to Microsoft Excel.",
  },

  // ===================
  // ARCHIVES
  // ===================
  zip: {
    id: "zip",
    category: "archive",
    displayName: "ZIP Archive",
    extensions: ["zip"],
    mimeTypes: ["application/zip", "application/x-zip-compressed"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip"],
    supportedOptions: {
      compressionLevel: true,
    },
    preview: true,
    compression: true,
    metadata: false,
    seoSlug: "zip",
    description: "Standard lossless data compression and archive format bundling multiple files and directories.",
  },
  tar: {
    id: "tar",
    category: "archive",
    displayName: "TAR Tape Archive",
    extensions: ["tar"],
    mimeTypes: ["application/x-tar"],
    canInput: true,
    canOutput: true,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip"],
    preview: true,
    compression: false,
    metadata: false,
    seoSlug: "tar",
    description: "Consolidated archive file format widely used on Unix and Linux systems.",
  },
  rar: {
    id: "rar",
    category: "archive",
    displayName: "RAR Archive",
    extensions: ["rar"],
    mimeTypes: ["application/vnd.rar", "application/x-rar-compressed"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "server",
    engines: ["unrar"],
    preview: false,
    compression: false,
    metadata: false,
    seoSlug: "rar",
    description: "Proprietary compressed archive file format supporting multi-part volumes.",
  },
  "7z": {
    id: "7z",
    category: "archive",
    displayName: "7-Zip Archive",
    extensions: ["7z"],
    mimeTypes: ["application/x-7z-compressed"],
    canInput: true,
    canOutput: false,
    status: "BETA",
    processingMode: "server",
    engines: ["7zip"],
    preview: false,
    compression: true,
    metadata: false,
    seoSlug: "7z",
    description: "High-compression ratio open archive format developed by Igor Pavlov.",
  },

  // ===================
  // EBOOKS
  // ===================
  epub: {
    id: "epub",
    category: "ebook",
    displayName: "EPUB E-Book",
    extensions: ["epub"],
    mimeTypes: ["application/epub+zip"],
    canInput: true,
    canOutput: false,
    status: "AVAILABLE",
    processingMode: "browser",
    engines: ["jszip", "html"],
    preview: true,
    compression: false,
    metadata: true,
    seoSlug: "epub",
    description: "Standard open electronic book format widely used across e-readers and mobile apps.",
  },
  mobi: {
    id: "mobi",
    category: "ebook",
    displayName: "Mobipocket E-Book",
    extensions: ["mobi"],
    mimeTypes: ["application/x-mobipocket-ebook"],
    canInput: true,
    canOutput: false,
    status: "COMING_SOON",
    processingMode: "server",
    engines: ["calibre"],
    preview: false,
    compression: false,
    metadata: true,
    seoSlug: "mobi",
    description: "Legacy Amazon Kindle compatible e-book format.",
  },

  // ===================
  // FONTS
  // ===================
  ttf: {
    id: "ttf",
    category: "font",
    displayName: "TrueType Font",
    extensions: ["ttf"],
    mimeTypes: ["font/ttf", "application/x-font-ttf"],
    canInput: true,
    canOutput: false,
    status: "COMING_SOON",
    processingMode: "server",
    engines: ["fontforge"],
    preview: false,
    compression: false,
    metadata: false,
    seoSlug: "ttf",
    description: "Digital font standard originally developed by Apple and Microsoft.",
  },
  woff2: {
    id: "woff2",
    category: "font",
    displayName: "WOFF2 Web Font",
    extensions: ["woff2"],
    mimeTypes: ["font/woff2"],
    canInput: true,
    canOutput: false,
    status: "COMING_SOON",
    processingMode: "server",
    engines: ["woff2_compress"],
    preview: false,
    compression: true,
    metadata: false,
    seoSlug: "woff2",
    description: "Next-generation web font format providing roughly 30% smaller sizes than standard WOFF.",
  },
};

/**
 * Return all formats array
 */
export function getAllFormats(): FormatDefinition[] {
  return Object.values(FORMAT_REGISTRY);
}

/**
 * Find format by extension or MIME type
 */
export function getFormatById(id: string): FormatDefinition | undefined {
  return FORMAT_REGISTRY[id.toLowerCase()];
}

export function getFormatByExtension(ext: string): FormatDefinition | undefined {
  const normalized = ext.toLowerCase().replace(/^\./, "");
  return Object.values(FORMAT_REGISTRY).find((f) =>
    f.extensions.includes(normalized) || f.aliases?.includes(normalized)
  );
}

export function getFormatByMimeType(mime: string): FormatDefinition | undefined {
  const normalized = mime.toLowerCase();
  return Object.values(FORMAT_REGISTRY).find((f) =>
    f.mimeTypes.includes(normalized)
  );
}
